#pragma config(Sensor, in1,    leftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    rightPot,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  claw,           sensorDigitalOut)
#pragma config(Motor,  port1,           rightRear,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightLift1,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightLift2,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           leftLift2,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftLift1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftRear,      tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void driveArcade(int y, int x)
{
	motor[leftFront] = motor[leftRear] = y + x;
	motor[rightFront] = motor[rightRear] = .7/.85*y - x;
}

void driveMecanum(int y, int x, int r)
{
	motor[leftFront] = y + x - r;
	motor[leftRear] = y + x + r;
	motor[rightFront] = y - x + r;
	motor[rightRear] = y - x - r;
}

void setLiftSpeed(int y)
{
	motor[rightLift1] = motor[rightLift2] = y;
	motor[leftLift1] = motor[leftLift2] = y;

	//to other programmers, "leftArm" refers to both left arm motors and "rightArm" refers to both right arm motors --Mason
}

void setClaw(int y)
{
	SensorValue[claw] = y;
}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	driveArcade(127, 0);
	wait1Msec(1000); //1 second
	driveArcade(0,0);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		bool tankdrive = false; //enable tankdrive??? -- FOR DEBUGGING
		int button6Uvalue = 0;
		while (tankdrive==false)
		{
			int DriveX = vexRT[Ch4]; //sets drive speed variables
			int DriveY = vexRT[Ch3];
			int rotation = vexRT[Ch1];

			int liftSpeed = vexRT[Ch2]; //sets liftspeed equal to vexRT[Ch2]
			//int liftCorrection = vexRT[Ch1];
			int clawVal = vexRT[Btn5U];

			if (abs(DriveY) < 5) DriveY = 0; // Deadband
			if (abs(DriveX) < 5) DriveX = 0; // Deadband
			if (abs(liftSpeed) < 5) liftSpeed = 0; //Deadband for lift

			//driveArcade(DriveY, DriveX); //drive arcade method
			driveMecanum(DriveY, DriveX, rotation);
			setLiftSpeed(liftSpeed); //lift speed method
			setClaw(clawVal);


		}

		while (tankdrive==true) //Tank Drive Option For Debugging DriveTrain
		{
			motor[leftRear] = motor[leftFront] = vexRT[Ch3];
			motor[rightRear] = motor[rightFront] = vexRT[Ch2];
			//liftSpeed = 0; //while in tankdrive mode, liftspeed cannot be used because vexRT[Ch2 is being used for driving]
		}




	}

	// This is the main execution loop for the user control program. Each time through the loop
	// your program should update motor + servo values based on feedback from the joysticks.

	// .....................................................................................
	// Insert user code here. This is where you use the joystick values to update your motors, etc.
	// .....................................................................................
}
