#pragma config(Motor,  port1,           RB,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           LB,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           RF,            tmotorVex393, openLoop)
#pragma config(Motor,  port4,           LF,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           RO,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           RI,            tmotorVex393, openLoop)
#pragma config(Motor,  port7,           LO,            tmotorVex393, openLoop)
#pragma config(Motor,  port8,           LI,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          Intake,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  motor[LF]=motor[LB]=127;
	motor[RF]=motor[RB]=127;
	//Forward in Autonomous
	wait1Msec(450);
	//For .45 seconds
	motor[LF]=motor[LB]=0;
	motor[RF]=motor[RB]=0;
	//then you stop.
	// .....................................................................................
  // Insert user code here.
  // .....................................................................................


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		motor[LF]=motor[LB]=vexRT[Ch3]-vexRT[Ch1];
		motor[RF]=motor[RB]=vexRT[Ch3]+vexRT[Ch1];
		motor[RO]=motor[RI]=motor[LO]=motor[LI]=vexRT[Btn6U]*127;
		motor[RO]=motor[RI]=motor[LO]=motor[LI]=-vexRT[Btn6D]*127;
		motor[Intake]=vexRT[Btn5U]*75-vexRT[Btn5D]*75;



	}
}
